Console.Clear();
Console.Write("Введите координату точки A(x): ");
double ax = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите координату точки A(y): ");
double ay = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите координату точки A(z): ");
double az = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите координату точки B(x): ");
double bx = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите координату точки B(y): ");
double by = Convert.ToDouble(Console.ReadLine());
Console.Write("Введите координату точки B(z): ");
double bz = Convert.ToDouble(Console.ReadLine());
double s = Math.Sqrt(Math.Pow(ax - bx, 2) + Math.Pow(ay - by, 2) + Math.Pow(az - bz, 2));
Console.WriteLine($"Расстояние между двумя точками равно {Math.Round(s, 2)}");